/*
  This function returns the wave array.
*/
function createWaves() {
  
  return [ // wave 1
          [{ type: 'b', path: tilemap.paths[0], spawnTime: 60 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 120 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 180 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 210 }],
           // wave 2
          [{ type: 'b', path: tilemap.paths[0], spawnTime: 60 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 100 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 140 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 180 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 220 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 260 }],
           // wave 3
          [{ type: 'b', path: tilemap.paths[1], spawnTime: 60 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 100 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 140 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 180 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 220 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 260 }],
           // wave 4
          [{ type: 'b', path: tilemap.paths[1], spawnTime: 60 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 110 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 140 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 180 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 210 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 260 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 290 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 340 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 380 }],
           // wave 5
          [{ type: 'b', path: tilemap.paths[0], spawnTime: 60 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 100 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 140 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 180 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 220 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 260 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 320 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 360 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 400 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 440 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 480 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 520 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 560 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 600 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 660 }],
           // wave 6
          [{ type: 'y', path: tilemap.paths[0], spawnTime: 60 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 100 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 140 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 180 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 220 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 260 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 320 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 360 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 400 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 440 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 480 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 520 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 560 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 600 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 660 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 700 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 740 }],
           // wave 7
          [{ type: 'b', path: tilemap.paths[0], spawnTime: 60 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 100 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 140 },
           { type: 'b', path: tilemap.paths[0], spawnTime: 180 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 220 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 260 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 300 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 340 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 380 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 420 }],
           // wave 8
          [{ type: 'b', path: tilemap.paths[1], spawnTime: 60 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 100 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 140 },
           { type: 'b', path: tilemap.paths[1], spawnTime: 180 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 220 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 260 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 300 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 340 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 380 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 420 }],
           // wave 9
          [{ type: 'y', path: tilemap.paths[1], spawnTime: 30 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 60 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 90 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 120 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 150 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 180 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 210 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 240 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 270 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 300 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 320 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 340 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 360 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 380 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 410 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 440 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 470 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 500 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 530 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 560 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 590 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 620 },
           { type: 'y', path: tilemap.paths[0], spawnTime: 650 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 670 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 690 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 710 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 730 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 750 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 770 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 800 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 830 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 860 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 890 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 920 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 950 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 980 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 1010 },
           { type: 'y', path: tilemap.paths[1], spawnTime: 1040 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1060 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1080 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1100 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1120 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1140 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1160 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 1180 }],
           // wave 10
          [{ type: 'o', path: tilemap.paths[1], spawnTime: 20 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 40 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 60 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 80 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 100 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 120 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 140 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 160 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 180 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 200 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 220 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 240 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 260 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 280 },
           { type: 'o', path: tilemap.paths[1], spawnTime: 300 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 320 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 340 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 360 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 380 },
           { type: 'o', path: tilemap.paths[0], spawnTime: 400 },
           { type: 'r', path: tilemap.paths[1], spawnTime: 500 },
           { type: 'r', path: tilemap.paths[1], spawnTime: 580 },
           { type: 'r', path: tilemap.paths[0], spawnTime: 660 },
           { type: 'r', path: tilemap.paths[0], spawnTime: 740 }]
        ];
}
